[% WRAPPER 'wrapper.phtml' title='PhotoRamp' h1='Import Photos' %]

<div class="main-area">
	Found <strong>[% remote_files_count %]</strong> images on memory card.<br>
	Of these, <strong>[% remote_files_not_on_local.size %]</strong> are new and have not yet been imported.<br>

	[% IF remote_files_count > 0 AND remote_files_not_on_local.size > 0 %]

	<hr class="hr1">

	<p class="note">
		Clicking on a preview will open the file in a new window.
		When finished, please close it and return to this one.
	</p>

	<div class="action-button">
		<button id="selectImportCopyAll">Mark all for Import (Copy)</button>
		<button id="selectImportMoveAll">Mark all for Import (Move)</button>
		<button id="selectDeleteAll"    >Mark all for Delete</button>
	</div>

	<form id="what-to-import" method="post" action="/import-submit">
	<div class="gallery">
	[% FOREACH file IN remote_files_not_on_local %]
		[% IF loop.index % 4 == 0 %]
		[% UNLESS loop.first %]</div>[% END %]
		<div class="row">
		[% END %]
					<div id="divBox-[% encode_u64(file) %]" class="box">
						<div class="image" style="position:relative">
							<div style="position:absolute; top: 1px; left: 1px; font-size: 12px; color: white;text-align:left;">[% dcim_relative(file) %]</div>
							[% IF file_is_image(file) %]
							<a class="ajaxAction" href="/user-open/[% encode_u64(file) %]">
								[% IF STASH.fast_server %]
								<img src="/user-file/[% encode_u64(file) %]">
								[% ELSE %]
								<img src="[% static_link('/icons/icon-previewloading-128px.png') %]" class="loading imgNum[% loop.index %]" data-img-u64path="[% encode_u64(file) %]">
								[% END %]
							</a>
							[% ELSIF file_is_video(file) %]
							<a class="ajaxAction" href="/user-open/[% encode_u64(file) %]">
								<img src="[% static_link('/icons/icon-filetypevideo-128px.png') %]" width="128" height="128">
							</a>
							[% ELSE %]
							<a class="ajaxAction" href="/user-open/[% encode_u64(file) %]">
								<img src="[% static_link('/icons/icon-filetypeunknown-128px.png') %]" width="128" height="128">
							</a>
							[% END %]
						</div>
						<div class="actions">
							<label><input type="checkbox" id="checkImport-[% encode_u64(file) %]" class="import" name="import-[% encode_u64(file) %]" value="import">Import</label>
							<label><input type="checkbox" id="checkDelete-[% encode_u64(file) %]" class="delete" name="delete-[% encode_u64(file) %]" value="delete">Delete</label>
						</div>
					</div>
	[% END %]
		</div>
	</div>
	</form>

	<script type="text/javascript">
		$().ready(function(){
			$('input.delete, input.import').on('click', function(){
				var fname    = this.id.substring(12)
				var importCb = '#checkImport-'+fname;
				var deleteCb = '#checkDelete-'+fname;
				if ($(deleteCb).prop('checked') && !$(importCb).prop('checked')) {
					$('#divBox-' + fname).addClass('will_be_lost');
				} else {
					$('#divBox-' + fname).removeClass('will_be_lost');
				}
			});

			$('#selectImportCopyAll').on('click', function(){
				fileList.forEach(function(element){
					$('#checkImport-' + element).prop("checked", "checked");
					$('#checkDelete-' + element).prop("checked", false);
					$('#divBox-' + element).removeClass('will_be_lost');
				});
			});

			$('#selectImportMoveAll').on('click', function(){
				fileList.forEach(function(element){
					$('#checkImport-' + element).prop("checked", "checked");
					$('#checkDelete-' + element).prop("checked", "checked");
					$('#divBox-' + element).removeClass('will_be_lost');
				});
			});

			$('#selectDeleteAll').on('click', function(){
				fileList.forEach(function(element){
					$('#checkImport-' + element).prop("checked", false);
					$('#checkDelete-' + element).prop("checked", "checked");
					$('#divBox-' + element).addClass('will_be_lost');
				});
			});
		});

		[% IF STASH.slow_server %]
		var pauseLength_ms = 100;
		$().ready(function(){
			setTimeout(loadNextImage, pauseLength_ms*2); // wait a bit longer for the first one.
		});
		function loadNextImage () {
			var img = $('img.loading').first();
			if (img) {
				$(img)
				.attr('src', '/user-file/' + $(img).attr('data-img-u64path'))
				.on('load', function() {
					$(this).removeClass('loading');
					if (!this.complete || typeof this.naturalWidth == "undefined" || this.naturalWidth == 0) {
						//console.log('broken image!');
					} else {
						//console.log('loaded!');
					}
				});
				return setTimeout(loadNextImage, pauseLength_ms);
			} else {
				return false;
			}
		}
		[% END %]

		function promptContinue () {
			// Count imports
			var toCopy = 0;
			var toMove = 0;
			var toLose = 0;

			fileList.forEach(function(element){
				if ($('#checkImport-' + element).prop("checked") && $('#checkDelete-' + element).prop("checked"))
					toMove++;
				else if ($('#checkImport-' + element).prop("checked") && !$('#checkDelete-' + element).prop("checked"))
					toCopy++;
				else if (!$('#checkImport-' + element).prop("checked") && $('#checkDelete-' + element).prop("checked"))
					toLose++;
			});

			if (toCopy + toMove + toLose == 0) {
				dmsDialog.alert("No files selected.");
				return false;
			}

			var message = [];
			if (toCopy > 0)
				message.push(toCopy + ' files will be copied to computer');
			if (toMove > 0)
				message.push(toMove + ' files will be moved to computer');
			if (toLose > 0)
				message.push(toLose + ' files will be DELETED entirely.')

			message.push('<b>Continue?</b>');

			// Show confirm dialog
			dmsDialog.confirm(message, function(OK){
				if (!OK)
					return false;
				$('form#what-to-import').submit();
			});
		};

		var fileList = [
			[% FOREACH file IN remote_files_not_on_local %]'[% encode_u64(file) %]'[% UNLESS loop.last %],[% END %]
			[% END %]
		];
	</script>

	<div class="action-button">
		<button onclick="promptContinue();">Proceed &gt;</button>
	</div>
	[% END # IF %]

	<hr class="hr1">
	<div class="action-button">
		<button onclick="goto('/')">&lt; Main Menu</button>
	</div>
</div>

[% END %]
