<html>
    <head>
        <style type="text/css">
            body {
                background-color: #EEE;
                font-family: Sans-Serif;
                padding: 1em;
                text-align: center;
            }
            div.main-nav button {
                display: block;
                padding: 0.5em 1em;
                margin:  1em;
                min-width: 30em;
                font-size: 115%;
                text-align: left;
                margin-left: auto;
                margin-right: auto;
            }
            div.main-nav button div.icon, div.main-nav button div.label {
                display: inline;
            }
            div.main-nav button img {
                padding-right: 1em;
            }
        </style>
        <title>Photo Helper 2</title>
    </head>
    <body>
        <h1>Welcome to Photo Helper 2</h1>
        <div class="main-nav">
            <button>
                <div class="icon">
                    <img align="middle" src="icon-import-96px.png" width="96" height="96" xstyle="border:1px solid blue">
                </div>
                <div class="label">
                    Import Images from Memory Card
                </div>
            </button>
            <button>
                <img align="middle" src="icon-clean-96px.png" width="96" height="96" xstyle="border:1px solid blue">
                Clean Up Memory Card
            </button>
            <button>
                <img align="middle" src="icon-timestamp-96px.png" width="96" height="96" xstyle="border:1px solid blue">
                Fix Timestamps on Memory Card
            </button>
            <button>
                <img align="middle" src="icon-organizecomputer-96px.png" width="96" height="96" xstyle="border:1px solid blue">
                Organize Images on My Computer
            </button>
        </div>
    </body>
</html>
