[% WRAPPER 'wrapper.phtml' title='Welcome to PhotoRamp' %]

<div class="main-nav">
    <button onclick="goto('/import')">
        <img align="middle" width="96" height="96" src="icons/icon-import-96px.png">
        Import Images from Memory Card
    </button>
    <button onclick="goto('/cleanup')">
        <img align="middle" width="96" height="96" src="icons/icon-clean-96px.png">
        Clean Up Memory Card
    </button>
    <button onclick="goto('/fix-timestamps')">
        <img align="middle" width="96" height="96" src="icons/icon-timestamp-96px.png">
        Fix Timestamps on Memory Card
    </button>
    <button onclick="goto('/organize-computer')">
        <img align="middle" width="96" height="96" src="icons/icon-organizecomputer-96px.png">
        Organize Images on My Computer
    </button>
</div>

[% END %]
