<!DOCTYPE html>
<html>
    <head>
        <!-- Main Style -->
        <link rel="stylesheet" href="[% static_link('css/photoramp.css') %]"/>

        <!-- (jQuery) -->
        <script type="text/javascript" src="[% static_link('jQuery/jquery-3.7.1.min.js') %]"></script>

        <!-- (dmsDialog)  -->
        <script type="text/javascript" src="[% static_link('dmsDialog/js/dmsDialog.js') %]"></script>
        <link rel="stylesheet" href="[% static_link('dmsDialog/css/dmsDialog.css') %]"/>

        <!-- (favicon) -->
        <link rel="icon" type="image/png" href="[% static_link('icons/favicon-64px.png') %]"/>

        <script type="text/javascript">
            function goto (loc) { window.location = loc; }
            function curtime_s() { return (new Date).getTime()/1000; }

            var checkInterval_ms         = [% check_interval OR '1000' %]
            var serverPid                = [% server_pid %];
            var messages                 = [];
            var checkMessagesTimeout     = setTimeout(checkMessages, checkInterval_ms);
            var checkMessagesRetries     = 0;
            var checkMessagesRetriesMax  = 16;
            var checkMessagesLastOkTime  = curtime_s();
            var checkMessagesMaxErrTime  = 30;
            var attemptedErrorRecovery  = false;

            function checkMessages(){
                $.ajax({
                    url: '/get-messages/server-' + serverPid,
                    timeout: checkInterval_ms*5,
                    success: function(data, textStatus, jqXHR) {
                        checkMessagesRetries    = 0;
                        checkMessagesLastOkTime = curtime_s();

                        if (attemptedErrorRecovery && data.server_pid == serverPid) {
                            attemptedErrorRecovery = false;
                            dmsDialog.pressCx();
                        }

                        if (data.messages && data.messages.length > 0) {
                            messages = messages.concat(data.messages);

                            var last_message = data.messages.pop();
                            if (last_message && last_message.user_message) {
                                $('#user-message').html(last_message.user_message);
                            }
                        }

                        messages.forEach(function(element) {
                            if (element.goto_url) {
                                window.location = element.goto_url;
                            }
                        });

                        if (data.server_pid != serverPid) {
                            dmsDialog.pressCx();
                            $('h1').html("Application Restarted");
                            $('div#main-content').hide();
                            $('div#brash-notice').show();
                        } else {
                            checkMessagesTimeout = setTimeout(checkMessages, checkInterval_ms);
                        }
                    },
                    error: function(){
                        if (attemptedErrorRecovery
                            && checkMessagesRetries >= checkMessagesRetriesMax
                            && (curtime_s() - checkMessagesLastOkTime) > checkMessagesMaxErrTime
                        ) {
                            console.log('Last message was received at ' + checkMessagesLastOkTime);
                            console.log('The time is now ' + curtime_s() + ' -- giving up');
                            dmsDialog.pressCx();
                            $('h1').html("Error");
                            $('div#main-content').hide();
                            $('div#crash-notice').show();
                        } else {
                            startErrorRecovery();
                        }
                    }
                })
            }

            function startErrorRecovery(){
                dmsDialog.wait(["Program is busy or not responding.", "Retrying..."]);
                attemptedErrorRecovery = true;
                setTimeout(function(){
                    checkMessagesRetries++;
                    checkMessages();
                }, checkMessagesTimeout*8);
            };

            $().ready(function(){
                $('a.ajaxAction').on('click', function(){
                    $.get(this.href);
                    return false;
                });
            });
        </script>

        <title>[% title %]</title>
    </head>
    <body>
        <div id="top-header">
            <div class="left">PhotoRamp</div>
            <div class="right"><a
                class="shutdown_link"
                [% UNLESS show_shutdown_link %]style="display:none;" [% END %]
                href="[% STASH.shutdown_url %]">Exit</a>
            </div>
        </div>
        <div id="main">
            <h1 id="h1">[% h1 OR title %]</h1>
            <div id="user-message"></div>
            <div id="main-content">
                [% content %]
            </div>
            <div id="crash-notice">
                <p>PhotoRamp has crashed! Please close the window and re-launch.</p>
            </div>
            <div id="brash-notice">
                <p>A different instance of PhotoRamp has been started. Please close this window or tab.</p>
            </div>
            [% IF REQUEST.flash %]<script type="text/javascript">dmsDialog.alert("[% REQUEST.flash %]");</script>[% END %]
            [% IF error_dialog  %]<script type="text/javascript">dmsDialog.alert("[% error_dialog  %]");</script>[% END %]
        </div>
    </body>
</html>
