<!DOCTYPE html>
<html>
    <head>
        <!-- (jQuery) -->
        <script type="text/javascript" src="jQuery/jquery-3.7.1.min.js"></script>

        <!-- (dmsDialog)  -->
        <script type="text/javascript" src="dmsDialog/js/dmsDialog.js"></script>
        <link rel="stylesheet" href="dmsDialog/css/dmsDialog.css"></link>

        <!-- (favicon) -->
        <link rel="icon" type="image/png" href="icons/favicon-64px.png">

        <script type="text/javascript">
            function goto (loc) {
                window.location = loc;
            }

            var checkInterval_ms        = [% check_interval OR '1000' %]
            var serverPid               = '[% server_pid %]';
            var messages                = [];
            //var lastReadMessageId      = [% REQUEST.param('last_read_message_id') OR -1 %];
            var checkMessagesTimeout    = setTimeout(checkMessages, checkInterval_ms);
            var checkMessagesRetries    = 0;
            var checkMessagesRetriesMax = 10;
            var attemptedErrorRecovery  = false;
            function checkMessages(){
                $.ajax({
                    url: '/get-messages/server-' + serverPid,
                    timeout: checkInterval_ms*2,
                    success: function(data, textStatus, jqXHR) {
                        checkMessagesRetries = 0;

                        messages = messages.concat(data.messages);

                        var last_message = data.messages.pop();
                        if (last_message && last_message.user_message) {
                            $('#user-message').html(last_message.user_message);
                        }

                        messages.forEach(function(element) {
                            if (element.goto_url) {
                                window.location = element.goto_url;
                            }
                        });

                        checkMessagesTimeout = setTimeout(checkMessages, checkInterval_ms);
                    },
                    error: function(){
                        if (attemptedErrorRecovery && checkMessagesRetries >= checkMessagesRetriesMax) {
                            dmsDialog.pressCx();
                            $('h1').html("Error");
                            $('div#main-content').hide();
                            $('div#crash-notice').show();
                        } else {
                            startErrorRecovery();
                        }
                    }
                })
            }

            function startErrorRecovery(){
                dmsDialog.wait(["Program is busy or not responding.", "Retrying..."]);
                setTimeout(function(){
                    checkMessagesRetries++;
                    attemptedErrorRecovery = true;
                    checkMessages();
                }, checkMessagesTimeout*2);
            };

            $().ready(function(){
                $('a.ajaxAction').on('click', function(){
                    $.get(this.href);
                    return false;
                });
            });
        </script>
        <style type="text/css">
            body {
                background-color: #EEE;
                font-family: Sans-Serif;
                padding: 1em;
                text-align: center;
            }

            div#crash-notice {
                display:none;
            }

            div.main-nav button {
                display: block;
                padding: 0.5em 1em;
                margin:  1em;
                min-width: 30em;
                font-size: 115%;
                text-align: left;
                margin-left: auto;
                margin-right: auto;
            }

            div.main-nav button div.icon, div.main-nav button div.label {
                display: inline;
            }

            div.main-nav button img {
                padding-right: 1em;
            }

            hr.hr1 {
                margin: 1em 5em;
                border-top: 1px solid #333;
                border-left: 0;
                border-right: 0;
                border-bottom: 0;
            }

            div.gallery {
                text-align: center;
                align-items: center;
                margin-left: auto;
                margin-right: auto;
            }

            div.gallery div.row {
                display: flex;
                align-items: center;
                justify-content: center;
            }

            div.gallery div.box {
                xflex: 1;
                border: 2px solid #222;
                height: 256px;
                width: 196px;
                box-sizing: border-box;

                display: flex;
                flex-direction: column;

                margin: 5px;
                background: #222;
            }

            div.gallery div.image {
                flex: 1;
                display: flex;
                align-items: center;
                justify-content: center;
            }

            div.gallery div.box img {
                max-width: 192px;
                max-height: 192px;
            }

            div.gallery div.box div.actions {
                background: #BBB;
                flex-shrink: 0;
                width: 100%;
            }

            div.action-button {
                margin: 2em;
            }
        </style>
        <title>[% title %]</title>
    </head>
    <body>
        <h1 id="h1">[% h1 OR title %]</h1>
        <div id="user-message"></div>
        <div id="main-content">
            [% content %]
        </div>
        <div id="crash-notice">
            <p>PhotoRamp has crashed! Please close the window and re-launch.</p>
        </div>
        [% IF REQUEST.flash %]<script type="text/javascript">dmsDialog.alert("[% REQUEST.flash %]");</script>[% END %]
        [% IF error_dialog  %]<script type="text/javascript">dmsDialog.alert("[% error_dialog  %]");</script>[% END %]
    </body>
</html>
